"""
GitHub Agent — coleta dados públicos da GitHub API para bramau9010.

Salva data/github.json com repos relevantes (nome, descrição, linguagem, stars, URL).
Não requer autenticação para repos públicos (rate limit: 60 req/hora por IP).
"""

import json
import logging
from datetime import datetime, timezone
from pathlib import Path

import requests

logging.basicConfig(level=logging.INFO, format="%(asctime)s [github_agent] %(message)s")
logger = logging.getLogger(__name__)

GITHUB_USERNAME = "bramau9010"
API_BASE = "https://api.github.com"
DATA_DIR = Path(__file__).parent.parent / "data"

# Repos a excluir (profile README e forks sem interesse)
EXCLUDED_REPOS = {GITHUB_USERNAME}  # repo com mesmo nome do usuário = profile README


def fetch_repos() -> list[dict]:
    url = f"{API_BASE}/users/{GITHUB_USERNAME}/repos"
    params = {"per_page": 100, "sort": "updated", "type": "owner"}
    headers = {"Accept": "application/vnd.github+json", "X-GitHub-Api-Version": "2022-11-28"}

    logger.info(f"Fetching repos for {GITHUB_USERNAME}...")
    response = requests.get(url, params=params, headers=headers, timeout=15)
    response.raise_for_status()

    repos = response.json()
    logger.info(f"Found {len(repos)} repos total")
    return repos


def filter_repos(repos: list[dict]) -> list[dict]:
    """Filtra repos relevantes: exclui forks, arquivados e o profile README."""
    filtered = []
    for repo in repos:
        name = repo.get("name", "")
        if name in EXCLUDED_REPOS:
            logger.info(f"Skipping profile README repo: {name}")
            continue
        if repo.get("fork"):
            logger.info(f"Skipping fork: {name}")
            continue
        filtered.append(repo)

    logger.info(f"After filtering: {len(filtered)} repos")
    return filtered


def normalize_repo(repo: dict) -> dict:
    """Extrai campos relevantes de um repo."""
    return {
        "name": repo["name"],
        "description": repo.get("description") or "",
        "language": repo.get("language") or "",
        "stars": repo.get("stargazers_count", 0),
        "forks": repo.get("forks_count", 0),
        "url": repo["html_url"],
        "topics": repo.get("topics", []),
        "updated_at": repo.get("updated_at", ""),
        "archived": repo.get("archived", False),
    }


def run() -> dict:
    """Entry point — retorna dict com repos coletados."""
    try:
        raw_repos = fetch_repos()
        filtered = filter_repos(raw_repos)
        normalized = [normalize_repo(r) for r in filtered]

        output = {
            "_meta": {
                "collected_at": datetime.now(timezone.utc).isoformat(),
                "source": "GitHub API — auto-generated by github_agent.py",
                "username": GITHUB_USERNAME,
                "total_repos": len(normalized),
            },
            "repos": normalized,
        }

        output_path = DATA_DIR / "github.json"
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(json.dumps(output, ensure_ascii=False, indent=2))
        logger.info(f"Saved {len(normalized)} repos → {output_path}")
        return output

    except requests.HTTPError as e:
        logger.error(f"GitHub API error: {e.response.status_code} — {e.response.text[:200]}")
        raise
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
        raise


if __name__ == "__main__":
    result = run()
    print(json.dumps(result["_meta"], indent=2))
